name: 'Build and Push Docker Image'
description: 'Build and push a Docker image to Docker Hub and DigitalOcean Registry'

inputs:
  service_name:
    description: 'Service name for the Docker image'
    required: true
  docker_username:
    description: 'Docker Hub username'
    required: true
  docker_password:
    description: 'Docker Hub password'
    required: true
  digital_ocean_token:
    description: 'Digital Ocean token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build project
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.docker_username }}/${{ inputs.service_name }}:latest
          ${{ inputs.docker_username }}/${{ inputs.service_name }}:${{ github.sha }}

    - name: Install doctl
      run: |
        echo "Installing doctl..."
        sudo snap install doctl

    - name: Authenticate with DigitalOcean
      run: |
        echo "Authenticating with DigitalOcean..."
        doctl auth init -t ${{ inputs.digital_ocean_token }}

    - name: Tag and Push Docker Image to DigitalOcean Registry
      run: |
        echo "Tagging and pushing Docker image to DigitalOcean..."
        REGISTRY_NAME="registry.digitalocean.com/Knowvus"
        docker tag ${{ inputs.docker_username }}/${{ inputs.service_name }}:latest $REGISTRY_NAME/${{ inputs.service_name }}:latest
        echo ${{ inputs.digital_ocean_token }} | docker login $REGISTRY_NAME -u doctl --password-stdin
        docker push $REGISTRY_NAME/${{ inputs.service_name }}:latest
