name: Build and Deploy Docker Image
description: 'Deploy Service to Docker Swarm as Manager'

runs:
  using: "composite"
  steps:
        - name: Check out code
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Docker Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

        - name: Create a temporary .env file on the runner node
          shell: bash
          run: |
            echo "INFISICAL_CLIENT_ID=${{ secrets.INFISICAL_CLIENT_ID }}" > .env
            echo "INFISICAL_SECRET=${{ secrets.INFISICAL_SECRET }}" >> .env
            echo "INFISICAL_PROJECT_ID=${{ secrets.INFISICAL_PROJECT_ID }}" >> .env
            cat .env

        - name: Copy files to Droplet
          uses: appleboy/scp-action@v0.1.3
          with:
            host: ${{ secrets.DO_DUKE_IP }}
            username: root
            password: ${{ secrets.DUKE_ROOT_PASSWORD }}
            source: ".env,docker-compose.yaml,Dockerfile"
            target: "/root/deployment_directory/"
            port: 22

        - name: SSH into Droplet and Deploy
          uses: appleboy/ssh-action@v0.1.3
          with:
            host: ${{ secrets.DO_DUKE_IP }}
            username: root
            password: ${{ secrets.DUKE_ROOT_PASSWORD }}
            script: |
              cd /root/deployment_directory

              # Verify .env file and deploy using Docker Compose
              cat .env
              docker-compose --env-file .env -f docker-compose.yaml pull
              docker-compose --env-file .env -f docker-compose.yaml up -d
            port: 22
            timeout: 5s
            command_timeout: 15s